export const EVENT_ACTION_TYPES = {
  SET_FORKS: 'SET_FORKS',
  SET_PULL_REQUESTS: 'SET_PULL_REQUESTS',
  SET_USER: 'SET_USER',
  EVENTS_HAS_ERRORED: 'EVENTS_HAS_ERRORED',
  EVENTS_IS_LOADING: 'EVENTS_IS_LOADING',
}
